export { Avatar }        from '@/components/ui/Avatar'
export { DashboardView } from './DashboardView'
export { Badge } from '@/components/ui/Badge'
export type { BadgeVariant } from '@/components/ui/Badge'
export { ClientsView } from './ClientsView'
export { DeactivateClientButton } from '@/features/clients/components/DeactivateClientButton'
export { LoadingSkeleton, CardSkeleton, StatSkeleton, Skeleton } from '@/components/ui/LoadingSkeleton'
export { InvoicesView }  from './InvoicesView'
export { MessagesView }  from '@/features/messaging/components/MessagesView'
export { ScheduleView } from './ScheduleView'
export { DashboardClientShell } from './DashboardClientShell'
export { UserMenuSheet } from './UserMenuSheet'
export { PilotBanner } from '@/components/ui/PilotBanner'
